#!/bin/bash

case "$1" in
  pre)
    echo "[wakeup-check] Pre-Suspend Start" >> /var/log/wakeup-check.log
    sudo /usr/local/bin/wakeup-check.sh pre
    echo "[wakeup-check] Pre-Suspend End" >> /var/log/wakeup-check.log
    ;;
  post)
    echo "[wakeup-check] Post-Resume Start" >> /var/log/wakeup-check.log
    sudo /usr/local/bin/wakeup-check.sh post
    echo "[wakeup-check] Post-Resume End" >> /var/log/wakeup-check.log
    ;;
esac

exit 0
